--------------------------------------------------------------------------------
-- Painel PDV C5 SN — objetos do schema PAINELPDVC5IA
--
-- Este script NAO deve ser executado por mim (Claude). Preparado apenas para
-- revisao e execucao manual por voce.
--
-- Nomenclatura das tabelas conforme definido por voce (2ª rodada de revisao).
--
-- Escopo: apenas objetos proprios da aplicacao. Identidade e senha do
-- Consinco continuam em CONSINCO.GE_USUARIO / CONSINCO.GE_MEMBRO, expostos
-- via PAINELPDVC5IA.VW_USUARIOS (sem NROEMPRESA agora). As empresas
-- (lojas/checkouts ativos) vem de PAINELPDVC5IA.VW_EMPRESAS
-- (CONSINCOMONITOR.TB_EMPRESA + TB_CHECKOUT). Este schema NUNCA grava nada
-- nos schemas Consinco/ConsincoMonitor.
--
-- Pre-requisitos ja atendidos (informado por voce):
--   * Owner PAINELPDVC5IA criado.
--   * GRANT SELECT em PAINELPDVC5IA.VW_USUARIOS, VW_MONITORAMENTO, VW_EMPRESAS.
--   * GRANT EXECUTE em CONSINCO.STA_PKG_SEGURANCA (para a funcao DECODIFICAR).
--------------------------------------------------------------------------------

-- TB_ROLES: perfis de acesso (ex.: ADMIN, VISUALIZADOR). Independente das
-- empresas/grupos do Consinco — controla apenas o que o usuario ve dentro
-- do Painel.
CREATE TABLE TB_ROLES (
    ID              NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CODIGO          VARCHAR2(50)    NOT NULL,
    NOME            VARCHAR2(100)   NOT NULL,
    DESCRICAO       VARCHAR2(255),
    CRIADO_EM       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    ATUALIZADO_EM   TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_TB_ROLES_CODIGO UNIQUE (CODIGO)
);

COMMENT ON TABLE TB_ROLES IS 'Perfis de acesso do Painel PDV C5 SN (ex.: ADMIN).';

-- TB_PERMISSOES: catalogo de permissoes granulares por menu/funcionalidade/acao.
-- Chave textual estavel (ex.: 'monitoramento_caixas.view') referenciada pelo
-- middleware de autorizacao no backend.
CREATE TABLE TB_PERMISSOES (
    ID              NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CHAVE           VARCHAR2(150)   NOT NULL,
    DESCRICAO       VARCHAR2(255)   NOT NULL,
    CRIADO_EM       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_TB_PERMISSOES_CHAVE UNIQUE (CHAVE)
);

COMMENT ON TABLE TB_PERMISSOES IS 'Catalogo de permissoes granulares (menu/funcionalidade/acao).';

-- TB_ROLES_PERMISSOES: associacao N:N entre perfis e permissoes.
-- OBS: o perfil ADMIN nao precisa (nem deve) ser populado aqui — o backend
-- concede bypass total pra quem tem o role ADMIN, de forma centralizada, pra
-- que permissoes criadas no futuro fiquem automaticamente disponiveis ao
-- administrador sem exigir um INSERT manual a cada nova funcionalidade.
CREATE TABLE TB_ROLES_PERMISSOES (
    ROLE_ID         NUMBER NOT NULL,
    PERMISSAO_ID    NUMBER NOT NULL,
    CONSTRAINT PK_TB_ROLES_PERMISSOES PRIMARY KEY (ROLE_ID, PERMISSAO_ID),
    CONSTRAINT FK_ROLPERM_ROLE FOREIGN KEY (ROLE_ID) REFERENCES TB_ROLES (ID) ON DELETE CASCADE,
    CONSTRAINT FK_ROLPERM_PERMISSAO FOREIGN KEY (PERMISSAO_ID) REFERENCES TB_PERMISSOES (ID) ON DELETE CASCADE
);

-- TB_REGRAS_USUARIOS: vincula o CODUSUARIO (identidade vinda de
-- CONSINCO.GE_USUARIO, exposta em PAINELPDVC5IA.VW_USUARIOS) a um ou mais
-- perfis do Painel. Sem FK para a view de usuarios (view nao suporta FK) —
-- a validacao de que o codusuario existe de fato acontece em tempo de
-- login, no backend.
--
-- O usuario "admin" (acesso do desenvolvedor) NAO tem linha aqui — a role
-- dele e resolvida em codigo/env, nunca em tabela (ver observacao no final
-- do arquivo e o .env.example do backend).
CREATE TABLE TB_REGRAS_USUARIOS (
    CODUSUARIO      VARCHAR2(30)    NOT NULL,
    ROLE_ID         NUMBER          NOT NULL,
    ATRIBUIDO_EM    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    ATRIBUIDO_POR   VARCHAR2(30),
    CONSTRAINT PK_TB_REGRAS_USUARIOS PRIMARY KEY (CODUSUARIO, ROLE_ID),
    CONSTRAINT FK_REGRAUSU_ROLE FOREIGN KEY (ROLE_ID) REFERENCES TB_ROLES (ID) ON DELETE CASCADE
);

CREATE INDEX IX_TB_REGRAS_USUARIOS_COD ON TB_REGRAS_USUARIOS (CODUSUARIO);

-- TB_USUARIOS_EMPRESAS: quais empresas (PAINELPDVC5IA.VW_EMPRESAS —
-- NROEMPRESA/NOMEREDUZIDO) cada CODUSUARIO pode enxergar nas telas do
-- Painel (ex.: Monitoramento de Caixas). Sem isso, um usuario comum nao
-- ve NENHUMA empresa — precisa ser liberado explicitamente. ADMIN enxerga
-- todas, sempre, sem precisar de linha aqui (mesma logica do bypass de
-- permissao). Join com VW_EMPRESAS feito por NROEMPRESA.
--
-- NOME SUGERIDO — ajuste se preferir outro, e so avisar.
CREATE TABLE TB_USUARIOS_EMPRESAS (
    CODUSUARIO      VARCHAR2(30)    NOT NULL,
    NROEMPRESA      NUMBER          NOT NULL,
    ATRIBUIDO_EM    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    ATRIBUIDO_POR   VARCHAR2(30),
    CONSTRAINT PK_TB_USUARIOS_EMPRESAS PRIMARY KEY (CODUSUARIO, NROEMPRESA)
);

CREATE INDEX IX_TB_USUARIOS_EMPRESAS_COD ON TB_USUARIOS_EMPRESAS (CODUSUARIO);

-- TB_LOCAL_ADMIN_CREDENCIAL: credencial local de contingencia para OUTRAS
-- contas que, no futuro, precisem autenticar sem depender do fluxo
-- Consinco (o "admin" do desenvolvedor NAO usa esta tabela — ver observacao
-- no final do arquivo). Guarda hash bcrypt — nunca a senha em texto puro.
-- Desativar um acesso local = ATIVO='N' (nao precisa apagar a linha).
CREATE TABLE TB_LOCAL_ADMIN_CREDENCIAL (
    CODUSUARIO      VARCHAR2(30)    NOT NULL PRIMARY KEY,
    SENHA_HASH      VARCHAR2(255)   NOT NULL,
    ATIVO           CHAR(1)         DEFAULT 'S' NOT NULL,
    ATUALIZADO_EM   TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_TB_LOCAL_ADMIN_ATIVO CHECK (ATIVO IN ('S', 'N'))
);

COMMENT ON TABLE TB_LOCAL_ADMIN_CREDENCIAL IS 'Credencial local de contingencia (break-glass) para contas que nao sejam o admin do desenvolvedor, fora do fluxo Consinco.';

-- TB_TOKENS_REFRESH: sessao de longa duracao (renovacao do access token).
-- Guarda apenas o HASH do token (SHA-256), nunca o token em si — assim como
-- senha, um dump da tabela nao permite reconstituir uma sessao valida.
CREATE TABLE TB_TOKENS_REFRESH (
    ID              NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CODUSUARIO      VARCHAR2(30)    NOT NULL,
    TOKEN_HASH      VARCHAR2(64)    NOT NULL,
    CRIADO_EM       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    EXPIRA_EM       TIMESTAMP       NOT NULL,
    REVOGADO_EM     TIMESTAMP,
    IP_ORIGEM       VARCHAR2(45),
    USER_AGENT      VARCHAR2(255),
    CONSTRAINT UQ_TB_TOKENS_REFRESH_HASH UNIQUE (TOKEN_HASH)
);

CREATE INDEX IX_TB_TOKENS_REFRESH_COD ON TB_TOKENS_REFRESH (CODUSUARIO);

-- TB_INFORMACAOAPLICACAO: trilha de auditoria de seguranca (login, logout,
-- acesso negado, mudanca de permissao, operacoes administrativas). Nunca
-- contem senha/token em texto puro — apenas metadados do evento.
CREATE TABLE TB_INFORMACAOAPLICACAO (
    ID              NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CODUSUARIO      VARCHAR2(30),
    ACAO            VARCHAR2(100)   NOT NULL,
    RECURSO         VARCHAR2(255),
    RESULTADO       VARCHAR2(20)    NOT NULL,
    DETALHE         VARCHAR2(4000),
    IP_ORIGEM       VARCHAR2(45),
    CRIADO_EM       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_TB_INFOAPLIC_RESULTADO CHECK (RESULTADO IN ('SUCESSO', 'FALHA', 'NEGADO'))
);

CREATE INDEX IX_TB_INFOAPLIC_COD ON TB_INFORMACAOAPLICACAO (CODUSUARIO);
CREATE INDEX IX_TB_INFOAPLIC_CRIADO_EM ON TB_INFORMACAOAPLICACAO (CRIADO_EM);

-- TB_VERSOES_APLICACAO / TB_HISTORICOALTERACAO: historico de versoes
-- exibido ao usuario (linguagem simples) e, pra quem tiver a permissao,
-- tambem a visao tecnica.
--
-- NOME SUGERIDO para TB_VERSOES_APLICACAO — voce nao tinha renomeado essa
-- (so a de itens do changelog), ajustei pra manter o padrao; troque se
-- quiser outro nome.
CREATE TABLE TB_VERSOES_APLICACAO (
    ID              NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VERSAO          VARCHAR2(20)    NOT NULL,
    LANCADO_EM      DATE            NOT NULL,
    CONSTRAINT UQ_TB_VERSOES_VERSAO UNIQUE (VERSAO)
);

CREATE TABLE TB_HISTORICOALTERACAO (
    ID                  NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VERSAO_ID           NUMBER          NOT NULL,
    CATEGORIA           VARCHAR2(50)    NOT NULL,
    DESCRICAO_USUARIO   VARCHAR2(1000)  NOT NULL,
    DESCRICAO_TECNICA   VARCHAR2(2000),
    CONSTRAINT FK_HISTALT_VERSAO FOREIGN KEY (VERSAO_ID) REFERENCES TB_VERSOES_APLICACAO (ID) ON DELETE CASCADE,
    CONSTRAINT CK_HISTALT_CATEGORIA CHECK (CATEGORIA IN ('NOVIDADE', 'MELHORIA', 'CORRECAO'))
);

-- TB_PROGRESSOTUTORIALUSUARIO: controla, por usuario, quais tutoriais
-- guiados ja foram concluidos/dispensados (pra nao repetir e pra permitir
-- reabrir).
CREATE TABLE TB_PROGRESSOTUTORIALUSUARIO (
    CODUSUARIO      VARCHAR2(30)    NOT NULL,
    TUTORIAL_CHAVE  VARCHAR2(100)   NOT NULL,
    CONCLUIDO_EM    TIMESTAMP       NOT NULL,
    CONSTRAINT PK_TB_PROGRESSOTUTORIAL PRIMARY KEY (CODUSUARIO, TUTORIAL_CHAVE)
);

--------------------------------------------------------------------------------
-- SOBRE O USUARIO "admin"
--
-- Por pedido seu, o admin (acesso do desenvolvedor, mesmo conceito do
-- admin do NF-EntradaSN) NAO tem linha em NENHUMA tabela deste schema:
-- nem em TB_LOCAL_ADMIN_CREDENCIAL, nem em TB_REGRAS_USUARIOS.
--
-- A identidade, o hash da senha e a role ADMIN dele ficam resolvidos
-- inteiramente em codigo + variaveis de ambiente do backend
-- (ADMIN_CODUSUARIO / ADMIN_SENHA_HASH em backend/.env), num unico ponto
-- centralizado (backend/src/modules/auth/auth.service.ts) — diferente do
-- NF-EntradaSN, onde a senha do admin ficou hardcoded em texto puro e
-- espalhada em varios "if username === 'ADMIN'" pelo codigo. Aqui o valor
-- nunca aparece em texto puro em lugar nenhum (nem no .env, so o hash) e a
-- checagem de admin existe em um unico lugar.
--------------------------------------------------------------------------------
